//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroRhyme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class W_MusicDBEntities : DbContext
    {
        public W_MusicDBEntities()
            : base("name=W_MusicDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<list_Song> list_Song { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<StoreUp> StoreUp { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<u_song_list> u_song_list { get; set; }
        public virtual DbSet<UserCommentary> UserCommentary { get; set; }
        public virtual DbSet<w_Singer> w_Singer { get; set; }
        public virtual DbSet<w_singerType> w_singerType { get; set; }
        public virtual DbSet<w_Song> w_Song { get; set; }
        public virtual DbSet<w_SongType> w_SongType { get; set; }
        public virtual DbSet<w_User> w_User { get; set; }
    }
}
