//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroRhyme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_Singer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public w_Singer()
        {
            this.w_singerType = new HashSet<w_singerType>();
            this.w_Song = new HashSet<w_Song>();
        }
    
        public int singerID { get; set; }
        public string singerName { get; set; }
        public string singerimg { get; set; }
        public int isGroup { get; set; }
        public string singSex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_singerType> w_singerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_Song> w_Song { get; set; }
    }
}
